#!/usr/bin/env python3
"""Turn `tofu output -json` dumps into a static Ansible inventory fragment.

Reads files/tofu_{network,ceph,rke2}.json and (re)writes
inventory/generated.ini with the host groups derived from OpenTofu state.
"""
import json
import pathlib

ANSIBLE_DIR = pathlib.Path(__file__).resolve().parent.parent
FILES_DIR = ANSIBLE_DIR / "files"
INVENTORY_DIR = ANSIBLE_DIR / "inventory"

# (json dump file, [(tofu output name, ansible group name), ...])
SOURCES = [
    ("tofu_network.json", [("gateways", "gateways")]),
    ("tofu_ceph.json", [("ceph_nodes", "ceph")]),
    ("tofu_rke2.json", [("masters", "rke2_masters"), ("workers", "rke2_workers")]),
]


def main():
    lines = [
        "# Generated by scripts/gen_inventory.py from `tofu output -json`.",
        "# Do not edit by hand -- re-run after `tofu apply`.",
        "",
    ]
    for filename, mappings in SOURCES:
        path = FILES_DIR / filename
        # Emit an (empty) group header even when the tofu output is missing,
        # e.g. Ceph not deployed -- otherwise [ceph:vars] in inventory/static
        # refers to an undefined group and Ansible refuses to parse the file.
        data = json.loads(path.read_text()) if path.exists() else {}
        for output_name, group in mappings:
            nodes = data.get(output_name, {}).get("value", [])
            lines.append(f"[{group}]")
            for node in nodes:
                lines.append(f"{node['name']} ansible_ssh_host={node['ip']}")
            lines.append("")

    (INVENTORY_DIR / "generated.ini").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
