---

rke2_nic: "eth0"
rke2_channel: "stable"
rke2_version: "v1.36.2+rke2r1"
rke2_data_path: "/var/lib/rancher/rke2"
rke2_bin_path: "/usr/local/bin/rke2"
rke2_custom_manifests:
  - rke2-traefik-config.yaml

...
