---

- name: "First master | Configure RBAC for kube-vip"
  ansible.builtin.get_url:
    url: "https://kube-vip.io/manifests/rbac.yaml"
    dest: "{{ rke2_data_path }}/server/manifests/kube-vip-rbac.yaml"
    owner: "root"
    group: "root"
    mode: "0o644"

- name: "First master | Pull kube-vip image"
  ansible.builtin.shell:
    cmd: "crictl pull ghcr.io/kube-vip/kube-vip:{{ rke2_kubevip_tag }}"
  args:
    executable: /bin/bash
  environment:
    PATH: "/var/lib/rancher/rke2/bin:{{ ansible_env.PATH }}"
    CONTAINER_RUNTIME_ENDPOINT: "unix:///run/k3s/containerd/containerd.sock"
    CONTAINERD_ADDRESS: "/run/k3s/containerd/containerd.sock"
  changed_when: true

- name: "First master | Generate kube-vip manifest and let RKE2 install it"
  ansible.builtin.shell: |
    set -o pipefail
    ctr --namespace k8s.io run --rm --net-host ghcr.io/kube-vip/kube-vip:{{ rke2_kubevip_tag }} vip /kube-vip \
    manifest daemonset \
      --arp \
      --interface {{ rke2_nic }} \
      --address {{ rke2_vip }} \
      --controlplane \
      --leaderElection \
      --taint \
      --inCluster | tee /var/lib/rancher/rke2/server/manifests/kube-vip.yaml
  args:
    executable: /bin/bash
  environment:
    PATH: "/var/lib/rancher/rke2/bin:{{ ansible_env.PATH }}"
    CONTAINER_RUNTIME_ENDPOINT: "unix:///run/k3s/containerd/containerd.sock"
    CONTAINERD_ADDRESS: "/run/k3s/containerd/containerd.sock"
  changed_when: true

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

...
